### Build app using Maven
FROM docker.io/maven:3.9-amazoncorretto-24-al2023 AS build

WORKDIR /app

COPY . .

RUN mvn clean install -DskipTests


### Run app using Java 21
FROM docker.io/amazoncorretto:21.0.8-al2023-headless

WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

EXPOSE 8081

CMD ["java", "-jar", "app.jar"]